import type { Project } from "../types";

export const aiCalling: Project = {
  slug: "ai-calling",
  title: "AI Calling",
  oneLiner:
    "A real-time voice assistant designed around interruption, latency, and context — not a transcript of a chatbot.",
  year: "2025",
  role: "Product Designer",
  team: "Founding engineer + PM",
  platform: "Voice · Web",
  domain: "AI / Voice",
  index: 2,
  heroStyle: "conversation",
  impactLine: "Voice that can be interrupted without losing the thread.",
  explorerLabel: "Real-time voice",
  nextProject: "concentio",
  navItems: [
    { id: "overview", label: "Overview" },
    { id: "problem", label: "Problem" },
    { id: "conversation", label: "Conversation" },
    { id: "thinking", label: "Thinking" },
    { id: "impact", label: "Impact" },
  ],
  quickReadSectionIds: [
    "hero",
    "snapshot",
    "problem",
    "decisions",
    "impact",
    "next",
  ],
  sections: [
    {
      type: "hero",
      id: "hero",
      nav: "overview",
      kicker: "Case study · Real-time voice",
      title: "AI Calling",
      statement: "Let’s have a conversation — the product is the dialogue, not the page around it.",
    },
    {
      type: "snapshot",
      id: "snapshot",
      nav: "overview",
      description:
        "A real-time AI voice assistant for finding, confirming, and acting — while the other party is still speaking.",
      role: "Product Designer",
      timeline: "[ADD PROJECT TIMELINE]",
      team: "[ADD TEAM]",
      platform: "Voice · Real-time · Web companion",
      contribution:
        "Conversation states, interruption model, context retention, and a companion UI that makes listening / thinking / responding legible.",
    },
    {
      type: "problem",
      id: "problem",
      nav: "problem",
      kicker: "Problem",
      title: "Voice products fail in the gaps: barge-in, silence, and memory.",
      statement:
        "A chatbot read aloud is not a calling experience. People interrupt. They change their mind. They expect the system to keep up.",
      body: [
        "The hard parts are not the sentences. They are the states between sentences — listening, thinking, responding — and what happens when the user talks over the model.",
        "If those states are invisible, the product feels broken even when the model is correct.",
      ],
    },
    {
      type: "conversation",
      id: "conversation",
      nav: "conversation",
      title: "Let’s have a conversation.",
      intro:
        "Step through the call. Interrupt. Ask for clarification. Switch to text. The case study uses the same states as the product.",
      beats: [
        {
          id: "b1",
          speaker: "system",
          text: "Call connected. The assistant is listening.",
          state: "listening",
          reveals: "Problem: most voice UIs have no honest idle. Silence looks like failure.",
        },
        {
          id: "b2",
          speaker: "user",
          text: "Can you help me find a time that works for both teams next week?",
          reveals: "Context: the user arrives with a task, not a wake word.",
        },
        {
          id: "b3",
          speaker: "ai",
          text: "I can do that. I’ll check availability and keep the constraints you already mentioned.",
          state: "thinking",
          reveals: "Thinking is a first-class state — not a spinner on a webpage.",
        },
        {
          id: "b4",
          speaker: "ai",
          text: "Tuesday afternoon is open on one side, but Wednesday morning is the overlap.",
          state: "responding",
          reveals: "Response should be interruptible. Information arrives in turns, not a monologue.",
        },
        {
          id: "b5",
          speaker: "user",
          text: "Wait — Wednesday is a holiday for them.",
          reveals: "Interruption is the product. The system must stop, absorb, and continue.",
        },
        {
          id: "b6",
          speaker: "ai",
          text: "Understood. Dropping Wednesday. I’ll keep the original attendees and look at Thursday instead.",
          state: "responding",
          reveals: "Context retention: constraints persist without forcing the user to repeat the brief.",
        },
        {
          id: "b7",
          speaker: "system",
          text: "Outcome: the thread survived the interruption. The task moved.",
          reveals: "[ADD FINAL OUTCOME]",
        },
      ],
    },
    {
      type: "sticky-story",
      id: "states",
      nav: "thinking",
      title: "Three states. If any one is missing, trust collapses.",
      steps: [
        {
          id: "listening",
          kicker: "Listening",
          title: "The product has to look like it is receiving.",
          body: "An idle waveform is not decoration. It is proof the mic is open and the turn has not been stolen.",
          uiState: "listening",
        },
        {
          id: "thinking",
          kicker: "Thinking",
          title: "Latency needs a behavior, not an apology.",
          body: "A thinking state that still allows barge-in is more honest than a locked “generating” overlay.",
          uiState: "thinking",
        },
        {
          id: "responding",
          kicker: "Responding",
          title: "Speech is a stream. The UI should be too.",
          body: "Users cut in. The assistant yields, updates context, and resumes without restarting the task.",
          uiState: "responding",
        },
        {
          id: "held",
          kicker: "Held context",
          title: "Memory is an interface requirement.",
          body: "If the user has to restate the brief after an interruption, the product failed the call.",
          uiState: "outcome",
        },
      ],
    },
    {
      type: "decision-explorer",
      id: "decisions",
      nav: "thinking",
      title: "How interruption should feel",
      prompt: "When the user talks over the assistant, what should happen?",
      options: [
        {
          id: "a",
          label: "Option A · Finish the sentence anyway",
          status: "rejected",
          pros: ["Simpler audio pipeline", "Fewer incomplete thoughts"],
          cons: ["Feels rude", "Wastes time", "Trains people not to interrupt"],
          constraints: ["Real calls are overlapping by nature"],
          why: "Rejected: politeness in voice UI is yielding, not completing the script.",
        },
        {
          id: "b",
          label: "Option B · Hard stop and reset the turn",
          status: "considered",
          pros: ["Clear", "Easy to implement"],
          cons: ["Drops context", "User has to restart"],
          constraints: ["Tasks span multiple turns"],
          why: "Stop is necessary. Reset is not.",
        },
        {
          id: "c",
          label: "Option C · Yield, absorb, continue",
          status: "selected",
          pros: ["Matches human conversation", "Keeps the brief alive"],
          cons: ["Harder state machine", "Needs visible confirmation of what changed"],
          constraints: ["Must work with partial ASR and model latency"],
          why: "Selected: interruption updates the working context instead of discarding the call.",
        },
      ],
    },
    {
      type: "why-this-way",
      id: "why",
      nav: "thinking",
      title: "Why I designed it this way",
      intro: "Voice is a product surface. These were the decisions that kept it from becoming a chatbot with a speaker.",
      items: [
        {
          decision: "Make listening / thinking / responding visible.",
          context: "The model already had internal states. The UI did not.",
          tradeoff: "More chrome versus a mysterious pause.",
          reasoning: "Silence without a state is indistinguishable from a dropped call.",
          result: "Companion UI and audio-inspired motion share the same three states.",
        },
        {
          decision: "Treat interruption as a happy path.",
          context: "Most voice demos assume a clean turn-taking protocol.",
          tradeoff: "Engineering complexity versus a usable call.",
          reasoning: "People do not wait for a beep in real work.",
          result: "Yield → absorb → continue is the canonical flow.",
        },
        {
          decision: "Allow a switch to text without abandoning the thread.",
          context: "Some constraints are easier to type (names, IDs, times).",
          tradeoff: "Two modalities versus voice purity.",
          reasoning: "The task is the unit, not the microphone.",
          result: "Text is a mode of the same conversation, not a different product.",
        },
      ],
    },
    {
      type: "impact",
      id: "impact",
      nav: "impact",
      title: "What changed?",
      metrics: [
        { value: "[ADD METRIC]", label: "Successful interruptions recovered" },
        { value: "[ADD METRIC]", label: "Task completion on voice" },
        { value: "[ADD METRIC]", label: "Repeat-brief rate" },
      ],
      qualitative: [
        "The assistant can be cut off without collapsing the task.",
        "States are readable even with sound off — the portfolio uses the same idea.",
      ],
      before: ["Monologue", "Fragile turns", "Hidden latency"],
      after: ["Interruptible", "Held context", "Legible states"],
      business: "[ADD BUSINESS IMPACT]",
      user: "People talk the way they already talk on a call.",
      product: "A conversation state machine, not a form with speech-to-text.",
      design: "The case study is a working model of the product behavior.",
    },
    {
      type: "learnings",
      id: "learnings",
      nav: "impact",
      kicker: "Reflection",
      title: "If you cannot interrupt it, you cannot trust it.",
      body: [
        "Voice design is mostly the design of recovery.",
        "[ADD LEARNING FROM LAUNCH]",
      ],
    },
    { type: "next-project", id: "next" },
  ],
};
