import type { Project } from "../types";

export const concentio: Project = {
  slug: "concentio",
  title: "Concentio",
  oneLiner:
    "An enterprise system for coordinating complex operational work across people, product, and data.",
  year: "2024",
  role: "Product Designer",
  team: "Ops + engineering pod",
  platform: "Web · Enterprise",
  domain: "Enterprise / Systems",
  index: 3,
  heroStyle: "system",
  impactLine: "A map of the work, not another queue of tickets.",
  explorerLabel: "Enterprise system",
  nextProject: "auriga",
  navItems: [
    { id: "overview", label: "Overview" },
    { id: "problem", label: "Problem" },
    { id: "system", label: "System" },
    { id: "design", label: "Design" },
    { id: "thinking", label: "Thinking" },
    { id: "impact", label: "Impact" },
  ],
  quickReadSectionIds: [
    "hero",
    "snapshot",
    "problem",
    "decisions",
    "why",
    "impact",
    "next",
  ],
  sections: [
    {
      type: "hero",
      id: "hero",
      nav: "overview",
      kicker: "Case study · Enterprise system",
      title: "Concentio",
      statement:
        "When the work spans teams and systems, the interface has to be a map — not a thinner version of someone else’s inbox.",
    },
    {
      type: "snapshot",
      id: "snapshot",
      nav: "overview",
      description:
        "Enterprise software for moving operational work from people, through product, into data, and back as a decision.",
      role: "Product Designer",
      timeline: "[ADD PROJECT TIMELINE]",
      team: "[ADD TEAM]",
      platform: "Web · Enterprise",
      contribution:
        "System architecture in the UI, workflow design, information hierarchy, and the interaction model for inspecting nodes of a live operation.",
    },
    {
      type: "problem",
      id: "problem",
      nav: "problem",
      kicker: "Problem",
      title: "The work was real. The product was a collection of disconnected tools.",
      statement:
        "Operators held the system in their heads. The software only held the tickets.",
      body: [
        "Each team optimized a local screen. Handoffs lived in chat. Exceptions were tribal knowledge.",
        "Adding another list would have made the local work faster and the whole slower.",
      ],
    },
    {
      type: "context",
      id: "context",
      nav: "problem",
      kicker: "Context",
      title: "[ADD COMPANY / PRODUCT CONTEXT]",
      body: [
        "The constraint was enterprise-typical: multiple roles, uneven data quality, and a need to act before the picture was complete.",
        "The design job was to make the path from user → workflow → product → data → output inspectable.",
      ],
    },
    {
      type: "system-map",
      id: "system",
      nav: "system",
      title: "The product is the map",
      intro:
        "Click a node. Each one holds a problem, a decision, and a piece of interface — the same way operators actually think.",
      nodes: [
        {
          id: "user",
          label: "User",
          problem: "Roles saw different slices of the same operation and could not reconcile them.",
          decision: "Start from the person and the job, not from the database table.",
          interfaceNote: "Role-aware entry, with the rest of the map still visible.",
          rationale: "Orientation beats a personalized void.",
        },
        {
          id: "workflow",
          label: "Workflow",
          problem: "Handoffs were implied. Exceptions had no home.",
          decision: "Make the path explicit, including the ugly branches.",
          interfaceNote: "A workflow that can be inspected mid-flight, not only in a diagram in Confluence.",
          rationale: "If the exception is common, it is the product.",
        },
        {
          id: "product",
          label: "Product",
          problem: "Screens optimized local tasks and hid upstream cause.",
          decision: "Every primary view sits on the map — not beside it.",
          interfaceNote: "Working canvas with a persistent system spine.",
          rationale: "Doing and understanding should not be different apps.",
        },
        {
          id: "agent",
          label: "Agent",
          problem: "Automation arrived as a black box in the middle of a human process.",
          decision: "Agents are nodes with inputs, outputs, and a reason they fired.",
          interfaceNote: "Automation is labeled, reversible, and attributable.",
          rationale: "Trust in enterprise automation is an interface problem.",
        },
        {
          id: "data",
          label: "Data",
          problem: "Source of truth was argued in meetings.",
          decision: "Show provenance next to the value, not in a lineage tool nobody opens.",
          interfaceNote: "Fields carry origin, freshness, and conflict.",
          rationale: "Operators already know data lies. The UI should say how.",
        },
        {
          id: "output",
          label: "Output",
          problem: "The “done” state was a exported file and a hope.",
          decision: "Outputs loop back into the map as objects that can be questioned.",
          interfaceNote: "Decisions, artifacts, and next actions remain in-product.",
          rationale: "A system that cannot inspect its own output will be bypassed.",
        },
      ],
    },
    {
      type: "sticky-story",
      id: "flow",
      nav: "design",
      title: "A single operation, four readings",
      steps: [
        {
          id: "p",
          kicker: "Step 01 · Problem",
          title: "The original view was a queue.",
          body: "Work appeared as items. Relationships between items were oral tradition.",
          uiState: "problem",
        },
        {
          id: "i",
          kicker: "Step 02 · Insight",
          title: "Operators were already running a system in their heads.",
          body: "The missing product was a shared picture of that system — not a prettier table.",
          uiState: "insight",
        },
        {
          id: "s",
          kicker: "Step 03 · Solution",
          title: "The map became the home screen.",
          body: "Local tools still exist. They open as inspections of a node, not as destinations that forget the rest.",
          uiState: "solution",
        },
        {
          id: "o",
          kicker: "Step 04 · Outcome",
          title: "Handoffs are visible before they fail.",
          body: "[ADD FINAL OUTCOME]",
          uiState: "outcome",
        },
      ],
    },
    {
      type: "exploration",
      id: "exploration",
      nav: "design",
      title: "The messy middle",
      intro: "Three structures were tested. The selected one is the one operators could teach back.",
      items: [
        {
          id: "e1",
          title: "Exploration 01 · Unified inbox",
          status: "rejected",
          tested: "One stream of work across teams.",
          outcome: "Familiar. Hid structure. Privileged whoever shouted in the stream.",
          learned: "Aggregation is not architecture.",
          influence: "Notifications remained, as a layer on the map — not as the product.",
        },
        {
          id: "e2",
          title: "Exploration 02 · Kanban of stages",
          status: "promising",
          tested: "Columns for each operational stage.",
          outcome: "Good for linear work. Brittle the moment an exception looped backward.",
          learned: "Boards flatten graphs.",
          influence: "Stage labels survived inside node detail.",
        },
        {
          id: "e3",
          title: "Exploration 03 · Live system map",
          status: "selected",
          tested: "User → workflow → product → agent → data → output as a working surface.",
          outcome: "Harder to learn in five minutes. Easier to run in the second week.",
          learned: "Enterprise products can ask for a first lesson if they repay it every day.",
          influence: "Shipped as the primary orientation — and as this case study’s interaction.",
        },
      ],
    },
    {
      type: "before-after",
      id: "before-after",
      nav: "design",
      title: "The surface of the work",
      beforeLabel: "Before",
      afterLabel: "After",
      beforeNote: "Queues, exports, and chat as the integration layer.",
      afterNote: "A map you can operate. Detail is an inspection, not a departure.",
    },
    {
      type: "decision-explorer",
      id: "decisions",
      nav: "thinking",
      title: "Should the map be the home, or a diagram in help?",
      prompt: "Where does the system picture live?",
      options: [
        {
          id: "a",
          label: "Option A · Documentation only",
          status: "rejected",
          pros: ["Zero product risk", "Looks clean in the app"],
          cons: ["Nobody maintains it", "Drifts from reality immediately"],
          constraints: ["The system changes weekly"],
          why: "A picture that is not the product will be wrong.",
        },
        {
          id: "b",
          label: "Option B · Optional overlay",
          status: "considered",
          pros: ["Safe rollout", "Power-user friendly"],
          cons: ["The people who need it most never find it"],
          constraints: ["New operators were the ones getting lost"],
          why: "Optional architecture is unused architecture.",
        },
        {
          id: "c",
          label: "Option C · Map as home",
          status: "selected",
          pros: ["Shared picture", "Handoffs have a place"],
          cons: ["Onboarding cost", "Requires ruthless simplification of nodes"],
          constraints: ["Could not show every system object on day one"],
          why: "Selected: the home screen teaches the company how it actually works.",
        },
      ],
    },
    {
      type: "why-this-way",
      id: "why",
      nav: "thinking",
      title: "Why I designed it this way",
      intro: "System design, stated as product decisions.",
      items: [
        {
          decision: "Put the map in the product, not in onboarding.",
          context: "Architecture slides already existed. Operators still got lost.",
          tradeoff: "A denser home versus a comforting empty state.",
          reasoning: "If the map is not operable, it is decoration.",
          result: "Orientation and action share a surface. [ADD METRIC]",
        },
        {
          decision: "Treat agents as nodes, not magic.",
          context: "Automation was being added in the middle of human workflows.",
          tradeoff: "Extra explanation versus silent speed.",
          reasoning: "Silent automation in enterprise is indistinguishable from a bug.",
          result: "Automation is attributable and reversible in the same map.",
        },
        {
          decision: "Show data provenance beside the value.",
          context: "Lineage lived in a specialist tool.",
          tradeoff: "Visual noise versus fewer arguments about “whose number.”",
          reasoning: "The argument was already happening. It deserved UI.",
          result: "Conflicts are visible before they become meetings.",
        },
        {
          decision: "Outputs remain objects.",
          context: "Done meant export.",
          tradeoff: "More objects to manage versus a dead-end PDF.",
          reasoning: "Work that cannot be questioned will be redone.",
          result: "[ADD FINAL OUTCOME]",
        },
      ],
    },
    {
      type: "impact",
      id: "impact",
      nav: "impact",
      title: "What changed?",
      metrics: [
        { value: "[ADD METRIC]", label: "Time to locate a handoff" },
        { value: "[ADD METRIC]", label: "Exception recovery" },
        { value: "[ADD METRIC]", label: "Onboarding to first independent run" },
      ],
      qualitative: [
        "The operation is visible as a system, not only as a queue.",
        "Automation and data conflicts have a place in the same picture.",
      ],
      before: ["Fragmented", "Oral handoffs", "Export as done"],
      after: ["Mapped", "Inspectable", "Output as object"],
      business: "[ADD BUSINESS IMPACT]",
      user: "Operators can teach the system by pointing at it.",
      product: "A living architecture instead of a suite of local tools.",
      design: "The case study interaction is the product interaction.",
    },
    {
      type: "learnings",
      id: "learnings",
      nav: "impact",
      kicker: "Reflection",
      title: "Enterprise UX is often just making the real system undeniable.",
      body: [
        "The map is not a flourish. It is the argument.",
        "[ADD LEARNING FROM LAUNCH]",
      ],
    },
    { type: "next-project", id: "next" },
  ],
};
